### ISSUE TITLE
The flow chart is not rendered in Lesson 1

### ISSUE THREAD

**Issue by premputtegowda** [muellerzr/Walk-with-fastai-revisited#2]
I believe this should be rendered as a flow chart (Lesson link: https://walkwithfastai.com/revisited/pets.html)

General Deep Learning Pipeline:
flowchart TD
    A[Gather Data] --> B[Clean Data]
    B --> C[Build `DataLoaders`]
    C ==> D[Build a `Learner`]
    D ==> E[Train with modern best practices]
    E ==> F[Deploy]
    F --> A
    E ==> C
We’ll be focusing on a small subset of this pipeline:

flowchart TD
    C["Build DataLoaders"] ==> D["Build a Learner"]
    D ==> E["Train with modern best practices"]
    E ==> F["Deploy"]
    E ==> C

**Comment by muellerzr** [comment]
Hi @premputtegowda, can you tell me more about the browser etc you're looking at this on? And can you try in a new private window? It's currently rendering for me :)

**Comment by muellerzr** [comment]
Whelp now it is broken so there is that :( 

Looks to be browser specific though. It breaks on Chrome but works on Edge

**Comment by muellerzr** [comment]
Fixed, just used svg's instead
